### ISSUE TITLE
Exception: No command at jumanpp

### ISSUE THREAD

**Issue by Ahmad-noborders** [cheripai/en-ja-translator#1]
Hi i have been trying to run this but going through following error
i have installed pyknp 0.3 and have also tried other versions but no luck
on my system python version is 3.6.9
Will appreciate any help

`Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "process_data.py", line 33, in normalize
    segmenter = JumanppWrapper(jumanpp=False)
  File "/home/abubakar/.local/lib/python3.6/site-packages/JapaneseTokenizer/jumanpp_wrapper/jumanpp_wrapper.py", line 165, in __init__
    self.jumanpp_obj = JumanppHnadler(jumanpp_command=command, timeout_second=timeout, pattern=pattern)  # type: JumanppHnadler
  File "/home/abubakar/.local/lib/python3.6/site-packages/JapaneseTokenizer/common/sever_handler.py", line 132, in __init__
    super(JumanppHnadler, self).__init__(command=jumanpp_command, option=option, pattern=pattern, timeout_second=timeout_second)
  File "/home/abubakar/.local/lib/python3.6/site-packages/JapaneseTokenizer/common/sever_handler.py", line 38, in __init__
    self.launch_process(command)
  File "/home/abubakar/.local/lib/python3.6/site-packages/JapaneseTokenizer/common/sever_handler.py", line 56, in launch_process
    raise Exception("No command at {}".format(command))
Exception: No command at jumanpp
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_data.py", line 132, in <module>
    en, ja, pairs = read_langs(c.EN_PATH, c.JA_PATH)
  File "process_data.py", line 53, in read_langs
    pairs += p.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
Exception: No command at jumanpp
`

**Comment by devsteppe9** [comment]
Hello @Ahmad-noborders 
For my understanding the problem is Japanese word tokenizer called JumanppWrapper. Maybe this package is no more exist. 
In my case I changed JumanppWrapper to janome tokenizer.

You can see my forked source code below:
[https://github.com/Jaha96/en-ja-translator/commit/bb9440ff0c2915d00ef4bc9c1b4461c21d689f59](https://github.com/Jaha96/en-ja-translator/commit/bb9440ff0c2915d00ef4bc9c1b4461c21d689f59)

**Comment by Ahmad-noborders** [comment]
> Hello @Ahmad-noborders
> For my understanding the problem is Japanese word tokenizer called JumanppWrapper. Maybe this package is no more exist.
> In my case I changed JumanppWrapper to janome tokenizer.
> 
> You can see my forked source code below:
> [Jaha96@bb9440f](https://github.com/Jaha96/en-ja-translator/commit/bb9440ff0c2915d00ef4bc9c1b4461c21d689f59)

Thanks you @Jaha96  problem resolved but where to find ja.tsv file?
i downloaded "data/glove.6B.300d.txt" from kaggle but cant fine ja.tsv
any help is appreaciated

**Comment by Ahmad-noborders** [comment]
> Hello @Ahmad-noborders
> For my understanding the problem is Japanese word tokenizer called JumanppWrapper. Maybe this package is no more exist.
> In my case I changed JumanppWrapper to janome tokenizer.
> 
> You can see my forked source code below:
> [Jaha96@bb9440f](https://github.com/Jaha96/en-ja-translator/commit/bb9440ff0c2915d00ef4bc9c1b4461c21d689f59)

thank you so much @Jaha96  it solved my problem. i really appreciate
